apiVersion: v1
kind: Service
metadata:
  name: back 
  labels:
    app.kubernetes.io/name: back
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app.kubernetes.io/name: back
    app.kubernetes.io/component: backend
