apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  selector:
    matchLabels:
      run: db-service
  replicas: 1
  template:
    metadata:
      labels:
        run: db-service
    spec:
      containers:
        - name: db
          image: db:local
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
              protocol: TCP
