apiVersion: v1
kind: Service
metadata:
  name: db 
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/component: backend
