apiVersion: v1
kind: Service
metadata:
  name: front 
  labels:
    app.kubernetes.io/name: front
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: front
    app.kubernetes.io/component: backend
