apiVersion: apps/v1
kind: Deployment
metadata:
  name: logr-deployment
  labels:
    app: logr
spec:
  selector:
    matchLabels:
      run: logr-service
  replicas: 1
  template:
    metadata:
      labels:
        run: logr-service
    spec:
      containers:
        - name: logr
          image: localhost:32000/logr:registry
          #imagePullPolicy: Never
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - name: test-pvc-ssd
              mountPath: /var/log/logr
      volumes:
        - name: test-pvc-ssd
          hostPath:
            path: /mnt/disk0
            type: Directory

