apiVersion: v1
kind: Service
metadata:
  name: logr 
  labels:
    app.kubernetes.io/name: logr
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app.kubernetes.io/name: logr
    app.kubernetes.io/component: backend
