"""empty message

Revision ID: bdbe3da40b0c
Revises: 
Create Date: 2023-01-24 11:16:04.287708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbe3da40b0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adj', sa.String(length=30), nullable=True),
    sa.Column('noun', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('greetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_greetings_adj'), ['adj'], unique=True)
        batch_op.create_index(batch_op.f('ix_greetings_noun'), ['noun'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_greetings_noun'))
        batch_op.drop_index(batch_op.f('ix_greetings_adj'))

    op.drop_table('greetings')
    # ### end Alembic commands ###
